"""Domain primitives for the real-estate deal intelligence system."""

from real_estate_helm.domain import (
    Address,
    Alert,
    AlertSeverity,
    AlertStatus,
    ApprovalRequest,
    ApprovalStatus,
    Assumption,
    Asset,
    AuditLogEntry,
    CapexItem,
    CashFlowRecord,
    CashFlowType,
    Comment,
    Coordinates,
    Deal,
    DealIdentity,
    DealStatus,
    DecisionEvent,
    DebtTerms,
    DevelopmentBudget,
    DevelopmentMilestone,
    DocumentPage,
    DocumentType,
    DocumentReference,
    ExtractedFact,
    FactReviewStatus,
    ImagerySnapshot,
    InvestmentDecision,
    Lease,
    LocationContextItem,
    LocationContextType,
    MarketComp,
    MilestoneStatus,
    NewsClassification,
    NewsEvent,
    NotificationChannel,
    Obligation,
    ObligationType,
    PermitEvent,
    PropertyRecord,
    PushNotification,
    RentRollEntry,
    Scenario,
    ScenarioType,
    SourceKind,
    SpreadsheetCell,
    SpreadsheetModel,
    Task,
    TaskStatus,
    Tenant,
    UploadedDocument,
    User,
    UserRole,
    WebSource,
)
from real_estate_helm.adapters import (
    HttpJsonGeocoder,
    HttpJsonImageryProvider,
    HttpJsonLocationContextProvider,
    HttpJsonMarketCompProvider,
    HttpJsonNewsProvider,
    HttpJsonPermitProvider,
    HttpJsonPropertyDataProvider,
    HttpJsonWebSourceProvider,
)
from real_estate_helm.api import ApiResponse, ApiRouter
from real_estate_helm.auth_api import AuthenticatedApiRouter
from real_estate_helm.backup import BackupManifest, BackupService, RetentionPolicy
from real_estate_helm.cash_flow_import import CashFlowImportResult, CashFlowImportService
from real_estate_helm.collaboration import CollaborationService
from real_estate_helm.crm_import import CrmImportResult, CrmImportService
from real_estate_helm.data_room import DataRoomImportResult, DataRoomImportService
from real_estate_helm.email_import import EmailDealImportService, EmailImportResult
from real_estate_helm.enrichment import EnrichmentService
from real_estate_helm.export_controls import (
    ExportControlPolicy,
    ExportDecision,
    ExportKind,
    redacted_deal_export,
)
from real_estate_helm.extraction import (
    calibrate_proposals,
    compare_spreadsheet_to_canonical,
    DocumentExtractionProvider,
    DocumentSummary,
    DocumentSummaryProvider,
    ExtractionProposal,
    ExtractionService,
    HttpJsonDocumentExtractionProvider,
    HttpJsonDocumentSummaryProvider,
    StaticDocumentExtractionProvider,
    StaticDocumentSummaryProvider,
    SpreadsheetComparisonRow,
)
from real_estate_helm.exports import render_cash_flow_xlsx, render_deal_summary_pdf, render_ic_memo_pptx
from real_estate_helm.fastapi_app import create_app
from real_estate_helm.intake import IntakeService
from real_estate_helm.notifications import (
    build_alert_notifications,
    HttpPushNotificationProvider,
    InMemoryNotificationProvider,
    NotificationDelivery,
    NotificationDeliveryService,
    NotificationProvider,
)
from real_estate_helm.obligation_import import ObligationImportResult, ObligationImportService
from real_estate_helm.schemas import (
    AddCashFlowRequest,
    AddDocumentRequest,
    AddFactRequest,
    ChangeStatusRequest,
    CreateDealRequest,
    ReviewFactRequest,
    ValidationError,
)
from real_estate_helm.postgres import (
    PostgresDealRepository,
    PostgresDealSqlMapper,
    PostgresMigrationRunner,
    SqlStatement,
)
from real_estate_helm.portfolio_qa import PortfolioAnswer, PortfolioQuestionAnswerer
from real_estate_helm.repository import JsonDealRepository
from real_estate_helm.reporting import (
    export_redacted_deal_json,
    generate_asset_monitoring_report_markdown,
    generate_development_progress_report_markdown,
    generate_monitoring_report_markdown,
    generate_portfolio_report_markdown,
    generate_lender_covenant_report_markdown,
    generate_monthly_performance_report_markdown,
    generate_rejected_deal_review_markdown,
)
from real_estate_helm.scenarios import export_scenario_csv, scenario_export_rows
from real_estate_helm.services import DealService
from real_estate_helm.security import (
    AccessGrant,
    AuthenticatedPrincipal,
    ObjectAccessPolicy,
    require_mfa,
    TokenAuthenticator,
    totp_code,
    verify_totp,
)
from real_estate_helm.settings import ProviderSettings, Settings, StorageSettings
from real_estate_helm.storage import (
    EncryptedObjectStorage,
    LocalObjectStorage,
    ObjectStorage,
    s3_storage_from_settings,
    S3CompatibleObjectStorage,
    S3Credentials,
    S3HttpClient,
    S3ObjectClient,
    StoredObject,
)
from real_estate_helm.tasks import TaskService
from real_estate_helm.workflows import (
    BackgroundWorkflowRuntime,
    RetryPolicy,
    ScheduledWorkflowRunner,
    WorkflowAttempt,
    WorkflowAttemptStore,
    WorkflowEngine,
    WorkflowLockStore,
    WorkflowRun,
    WorkflowSchedule,
)

__all__ = [
    "Assumption",
    "Address",
    "AccessGrant",
    "Alert",
    "AlertSeverity",
    "AlertStatus",
    "ApprovalRequest",
    "ApprovalStatus",
    "ApiResponse",
    "ApiRouter",
    "AuthenticatedApiRouter",
    "AuthenticatedPrincipal",
    "Asset",
    "AuditLogEntry",
    "BackupManifest",
    "BackupService",
    "BackgroundWorkflowRuntime",
    "build_alert_notifications",
    "calibrate_proposals",
    "CapexItem",
    "CashFlowRecord",
    "CashFlowType",
    "CashFlowImportResult",
    "CashFlowImportService",
    "AddCashFlowRequest",
    "AddDocumentRequest",
    "AddFactRequest",
    "CollaborationService",
    "Comment",
    "compare_spreadsheet_to_canonical",
    "Coordinates",
    "ChangeStatusRequest",
    "CreateDealRequest",
    "CrmImportResult",
    "CrmImportService",
    "DataRoomImportResult",
    "DataRoomImportService",
    "Deal",
    "DealIdentity",
    "DealStatus",
    "DecisionEvent",
    "DocumentReference",
    "DocumentPage",
    "DocumentExtractionProvider",
    "DocumentSummary",
    "DocumentSummaryProvider",
    "DebtTerms",
    "DevelopmentBudget",
    "DevelopmentMilestone",
    "DocumentType",
    "DealService",
    "EmailDealImportService",
    "EmailImportResult",
    "EnrichmentService",
    "EncryptedObjectStorage",
    "ExtractionProposal",
    "ExtractionService",
    "ExtractedFact",
    "ExportControlPolicy",
    "ExportDecision",
    "ExportKind",
    "export_redacted_deal_json",
    "export_scenario_csv",
    "FactReviewStatus",
    "generate_monitoring_report_markdown",
    "generate_asset_monitoring_report_markdown",
    "generate_development_progress_report_markdown",
    "generate_lender_covenant_report_markdown",
    "generate_monthly_performance_report_markdown",
    "generate_portfolio_report_markdown",
    "generate_rejected_deal_review_markdown",
    "HttpJsonGeocoder",
    "HttpJsonDocumentExtractionProvider",
    "HttpJsonDocumentSummaryProvider",
    "HttpJsonImageryProvider",
    "HttpJsonLocationContextProvider",
    "HttpJsonMarketCompProvider",
    "HttpJsonNewsProvider",
    "HttpJsonPermitProvider",
    "HttpJsonPropertyDataProvider",
    "HttpJsonWebSourceProvider",
    "HttpPushNotificationProvider",
    "ImagerySnapshot",
    "InMemoryNotificationProvider",
    "InvestmentDecision",
    "IntakeService",
    "JsonDealRepository",
    "Lease",
    "LocationContextItem",
    "LocationContextType",
    "LocalObjectStorage",
    "MarketComp",
    "MilestoneStatus",
    "NewsClassification",
    "NewsEvent",
    "NotificationChannel",
    "NotificationDelivery",
    "NotificationDeliveryService",
    "NotificationProvider",
    "ObjectStorage",
    "ObjectAccessPolicy",
    "Obligation",
    "ObligationImportResult",
    "ObligationImportService",
    "ObligationType",
    "PermitEvent",
    "PropertyRecord",
    "ProviderSettings",
    "PushNotification",
    "redacted_deal_export",
    "RentRollEntry",
    "RetentionPolicy",
    "require_mfa",
    "RetryPolicy",
    "ReviewFactRequest",
    "PostgresDealSqlMapper",
    "PostgresDealRepository",
    "PostgresMigrationRunner",
    "PortfolioAnswer",
    "PortfolioQuestionAnswerer",
    "render_cash_flow_xlsx",
    "render_deal_summary_pdf",
    "render_ic_memo_pptx",
    "create_app",
    "Scenario",
    "ScenarioType",
    "ScheduledWorkflowRunner",
    "scenario_export_rows",
    "Settings",
    "SourceKind",
    "SpreadsheetCell",
    "SpreadsheetComparisonRow",
    "SpreadsheetModel",
    "s3_storage_from_settings",
    "S3CompatibleObjectStorage",
    "S3Credentials",
    "S3HttpClient",
    "S3ObjectClient",
    "StaticDocumentExtractionProvider",
    "StaticDocumentSummaryProvider",
    "StoredObject",
    "StorageSettings",
    "SqlStatement",
    "Task",
    "TaskService",
    "TaskStatus",
    "Tenant",
    "TokenAuthenticator",
    "totp_code",
    "UploadedDocument",
    "User",
    "UserRole",
    "ValidationError",
    "verify_totp",
    "WebSource",
    "WorkflowEngine",
    "WorkflowAttempt",
    "WorkflowAttemptStore",
    "WorkflowLockStore",
    "WorkflowRun",
    "WorkflowSchedule",
]
